### ISSUE TITLE
no 

### ISSUE THREAD

**Issue by ebobo54** [ebobo54/Prog_2#2]
Traceback (most recent call last):
  File "lab_13.py", line 1, in <module>
    import toga
ModuleNotFoundError: No module named 'toga'

Traceback (most recent call last):
  File "lab_12.py", line 2, in <module>
    from pyforms.basewidget import BaseWidget
ModuleNotFoundError: No module named 'pyforms.basewidget'

**Comment by ebobo54** [comment]
Traceback (most recent call last):
  File "toga.py", line 1, in <module>
    import toga
  File "/home/user/Desktop/students/601-31/Gilev/Prog_2/toga.py", line 2, in <module>
    from toga.style import Pack
ModuleNotFoundError: No module named 'toga.style'; 'toga' is not a package
